### ISSUE TITLE
Add Zorya as submodule, amend setup

### ISSUE THREAD

**Issue by bonniegee** [RockefellerArchiveCenter/zodiac#133]
## Is your feature request related to a problem? Please describe.
Development on Zorya is near completion. It needs to be added as a microservice.

## Describe the solution you'd like
Add Zorya as a submodule. Amend setup_services.py to include Zorya.

**Comment by helrond** [comment]
When updating setup_services.py, also make sure to add a PeriodicTask for the Discover Bags in Zorya (this means adding that service to the `TASKS` list.

**Comment by helrond** [comment]
@bonniegee I'll take care of this as part of #152
