### ISSUE TITLE
Implement RAC Style Library

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/zodiac#245]
Where possible, replace local styles for the UI with the [RAC Style Library](https://github.com/RockefellerArchiveCenter/styles) styles: [https://assets.rockarch.org/v0.10.0/main.min.css](https://assets.rockarch.org/v0.8.1/main.min.css).

Update UI components to follow the [RAC Style Guide](https://styles.rockarch.org/).

**Comment by helrond** [comment]
Closing as won'tfix because this will be superseded by refactoring work.
